/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config = 
{
  address: '0.0.0.0',
  //port : 8080,
  ipWhitelist: [],
  modules: [
    {
      module: 'alert',
      config: {}
    },
    {
			module: "clock",
			position: "top_left",
      config:{
        timeFormat: 12,
        showPeriod: true,
        clockBold: true,
        displayType: 'both'
      }
		},
    {
    module: 'MMM-BackgroundSlideshow',
    position: 'fullscreen_below',
    config: {
      imagePaths: ['modules/MMM-BackgroundSlideshow/exampleImages/'],
      transitionImages: true,
      randomizeImageOrder: true
    }
  },
    /*{
		module: 'MMM-ImageSlideshow',
		position: 'bottom_right',
		config: {
			imagePaths: ['modules/MMM-ImageSlideshow/exampleImages']
		}},
  {
      disabled: false,
      module: "MMM-DigitalAlarmClock",
      position: "top_center",	
      config: {
        timezone: "America/Chicago",
        alarmSet: true,
        alarms: [
				{
					time: "09:30",
					days: [1, 2, 3, 4, 5],
					sound: "alarm.mp3",
				},
        {
					time: "15:47",
					days: [1, 2, 3],
          title: "Meditation Time",
					sound: "alarm.mp3"
				}
        ],
			sound: "alarm.mp3", 
			//touch: false,
			//snooze: false,
			//popup: true,
		}
	},*/
    {
      module: 'MMM-PrayerTime',
      header: 'Prayer Time',
      position: 'center',
      config: {
        lat: '51.509865',
        lon: '-0.118092',
        method: 4,
        alertTimer: 60000
      }
    },
    /*{
      module: 'MMM-RandomQuranAyah',
      header: 'Ayah of the day',
      position: 'bottom',
      config: {
        showArabic: true,
        surahArabicName: true,
        translationLang: 'ur.qadri'
      }
    },*/
    
    {
      module: 'MMM-Remote-Control',
      position: 'bottom_left',
      config: {
        showModuleApiMenu: true,
        secureEndpoints: true
      }
    }
  ],
  useHttps: false,
  httpsPrivateKey: '',
  httpsCertificate: '',
  locale: 'en-US'
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
